version: 1.0.{build}
image: Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
shallow_clone: true
before_build:
- cmd: nuget restore CenterCLR.NamingFormatter.sln
build:
  project: CenterCLR.NamingFormatter.sln
  parallel: true
  verbosity: minimal
